---
kind: pipeline
name: Antero

steps:
- name: execute 
  image: python:3.6
  commands:
  - pip install requests aiohttp async-timeout websockets yarl
  - NAME=Antero SERVER=192.168.85.196 PORT=8000 python client.py 


